### PR TITLE
Fix issue #3

### PR DESCRIPTION
**Pull request by daquexian**
It fixes issue https://github.com/onnx/optimizer/issues/3 by adding a unsqueeze op after the scalar bias

### CODE REVIEW

**Comment by linkerzhang** [comment]
will you also add test cases to cover it?

**Comment by askhade** [comment]
Please add description for your PR

**Comment by daquexian** [comment]
> will you also add test cases to cover it?

@linkerzhang Sure. I have added it.

**Comment by daquexian** [comment]
> Please add description for your PR

@askhade Done

**Review by linkerzhang — APPROVED** [review]

**Pull request merged**
