### PR TITLE
onnx optimizer init

### PR DESCRIPTION
**Pull request by daquexian**
Related issue: #1 

This PR contains the separate onnx optimizer library, in detail:

1. onnx optimizer codes and tests (optimizer_test.py) are copied from [onnx/onnx](https://github.com/onnx/onnx) to [onnx/optimizer](https://github.com/onnx/optimizer) with minimal changes to make the build successful. 
2. cmake codes and setup.py are added to build and install the python package and c++ library

An `onnxoptimizer`  (not sure whether it is a good name) package will be installed after running `pip3 install -e .`.
`pytest` passes.

### CODE REVIEW

**Comment by linkerzhang** [comment]
@daquexian thank you very much for making the change. are you going to setup CI for this repo please?

**Comment by daquexian** [comment]
@linkerzhang Thanks for your advice!

I have copied the azure pipeline ci yaml files from onnx/onnx repo and made some necessary changes for onnx/optimizer

Could you please set it up so that we can see whether the ci passes? Thanks!

**Comment by linkerzhang** [comment]
> @linkerzhang Thanks for your advice!
> 
> I have copied the azure pipeline ci yaml files from onnx/onnx repo and made some necessary changes for onnx/optimizer
> 
> Could you please set it up so that we can see whether the ci passes? Thanks!

I guess I don't have such access neither right now.
@prasanthpul can you offer @daquexian the permission to enable CI for optimizer repo please?

**Comment by prasanthpul** [comment]
Can you specify what you are looking for? Azure Pipelines is enabled for all repos under ONNX. I would also recommend using GitHub Actions

**Comment by daquexian** [comment]
> Can you specify what you are looking for? Azure Pipelines is enabled for all repos under ONNX. I would also recommend using GitHub Actions

I think a new pipeline needs to be added.

The step may be:

Click the "New Pipeline"

image

Select the correct repo, and select the "Existing Azure Pipelines YAML file"

image

**Comment by daquexian** [comment]
@prasanthpul I just noticed that there is no pipeline yaml in onnx/optimizer repo now since this PR has not been merged. So your help will be needed after this PR is merged :)

@linkerzhang I will setup and test the ci in my own repo (daquexian/optimizer) for now

**Comment by daquexian** [comment]
@linkerzhang The ci has passed: https://dev.azure.com/daquexian/onnx-optimizer/_build

**Comment by askhade** [comment]
@daquexian : Please prefer github actions for CIs. Azure pipelines and github actions are very similar and underneath they are based on same stack I believe... With github actions there is 1 layer less to interact. If you have a working azure pipeline CI then moving it to github actions should be trivial.

**Comment by daquexian** [comment]
> @daquexian : Please prefer github actions for CIs. Azure pipelines and github actions are very similar and underneath they are based on same stack I believe... With github actions there is 1 layer less to interact. If you have a working azure pipeline CI then moving it to github actions should be trivial.

I'll switch to github actions when I have time

**Comment by daquexian** [comment]
> @daquexian : Please prefer github actions for CIs. Azure pipelines and github actions are very similar and underneath they are based on same stack I believe... With github actions there is 1 layer less to interact. If you have a working azure pipeline CI then moving it to github actions should be trivial.

@askhade I have replaced azure pipelines to github actions in #7.

**Pull request merged**
