### PR TITLE
[LICENSE] add ALv2 licenses

### PR DESCRIPTION
**Pull request by szha**
Signed-off-by: Sheng Zha <zhasheng@amazon.com>

### CODE REVIEW

**Comment by daquexian** [comment]
@szha thanks! Is this pr ready to merge?

**Comment by szha** [comment]
Thanks for the quick response. The PR is not yet ready for merge. Let me make sure that there's no leftover MIT license. I will ping here once done.

**Comment by szha** [comment]
It should be in ready shape now. Thanks.

**Comment by daquexian** [comment]
@szha Thanks!

**Pull request merged**
